//
//  Element+AccessKey.swift
//  WebHTML
//  BSD 3-Clause License
//  Copyright 2023 Peter Cammeraat
//

public extension Element {
    /// The `accesskey` global attribute provides a hint for generating a keyboard shortcut for the current element.
    ///
    /// The attribute value must consist of a single printable character (which includes accented and other characters that can be generated by the keyboard).
    ///
    /// For more information, see [accesskey docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey)
    @discardableResult
    func accessKey(_ value: Character?, _ condition: Bool = true) -> Self {
        attribute("accesskey", value != nil ? String(value!) : nil, condition)
    }
}
